//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncidentStatus()
        {
            this.BoroughIncidents = new HashSet<BoroughIncident>();
        }
    
        public int IncidentStatusID { get; set; }
        public string IncidentStatusDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoroughIncident> BoroughIncidents { get; set; }
    }
}
