//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentType
    {
        public int IncidentTypeID { get; set; }
        public string IncidentTypeDesc { get; set; }
    }
}
